<a href="https://colab.research.google.com/github/sandhiyadurai/Data-Analytics/blob/main/numpy05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
l=[1,2,3,4,5,6]
type(l)
k=np.array(l)
type(k)
c= np.zeros((2,4)) # it show the cloumn and rows of a matrix ---- the output comes as zero
print(c)
a=np.ones((2,4)) # it showa as '1' in rows and column
print(a)
b= np.random.rand(3,3) # it show random number
print(b)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.64399029 0.24822161 0.13211703]
 [0.30311451 0.91313168 0.18981318]
 [0.73923576 0.31075259 0.37056244]]
[[ 7  9 11 14]
 [13 12  9  5]
 [ 8 11 11  5]
 [ 4  9  6 14]]


In [26]:
c=np.random.randint(3,15,size=(4,4)) # random matrix declared
print(c)

[[10  5  5 13]
 [ 6  5  7  3]
 [ 4 11  6  4]
 [12  5 14  6]]


In [42]:
d=np.random.choice((1,2,3,4,5,6,7)) # used to chose a random num that we entered
print(d)

4


In [54]:
e=np.full( (1,5,2,4),(3))
print(e)

[[[[3 3 3 3]
   [3 3 3 3]]

  [[3 3 3 3]
   [3 3 3 3]]

  [[3 3 3 3]
   [3 3 3 3]]

  [[3 3 3 3]
   [3 3 3 3]]

  [[3 3 3 3]
   [3 3 3 3]]]]


In [53]:
n=np.eye(4,k=-2) #--- egen matrix
print(n)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [62]:
v=np.arange(0,10,2) #---- range value
print(v)

[0 2 4 6 8]


In [65]:
a=np.linspace(0,13,5) #---- used to separate a value using given range of thirs num..(start,stop,num) num-- separate
print(a)

[ 0.    3.25  6.5   9.75 13.  ]


In [80]:
c=[1,2,3,4]
b=[3,4,5,6]
g=[3,5,6,7]
d=np.array([c,b,g])#---dim=dimension of the array
d.ndim
d.shape
d.size
d.dtype

dtype('int64')