<a href="https://colab.research.google.com/github/sandhiyadurai/Data-Analytics/blob/main/numpy07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=[1,2,3,4,5]
a=np.array(a)
a

array([1, 2, 3, 4, 5])

arthmetic opertion

In [2]:
import numpy as np
a=np.ones((4,4),dtype=int)
a=np.array(a)
a


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [6]:
a=np.eye((4),dtype=int)
a


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [9]:
a-1



array([[ 0, -1, -1, -1],
       [-1,  0, -1, -1],
       [-1, -1,  0, -1],
       [-1, -1, -1,  0]])

In [10]:
a+5


array([[6, 5, 5, 5],
       [5, 6, 5, 5],
       [5, 5, 6, 5],
       [5, 5, 5, 6]])

In [12]:
np.sin(a)

array([[0.74562414, 0.        , 0.        , 0.        ],
       [0.        , 0.74562414, 0.        , 0.        ],
       [0.        , 0.        , 0.74562414, 0.        ],
       [0.        , 0.        , 0.        , 0.74562414]])

In [13]:
np.tan(a)


array([[1.1189396, 0.       , 0.       , 0.       ],
       [0.       , 1.1189396, 0.       , 0.       ],
       [0.       , 0.       , 1.1189396, 0.       ],
       [0.       , 0.       , 0.       , 1.1189396]])

In [14]:
np.cos(a)

array([[0.66636675, 1.        , 1.        , 1.        ],
       [1.        , 0.66636675, 1.        , 1.        ],
       [1.        , 1.        , 0.66636675, 1.        ],
       [1.        , 1.        , 1.        , 0.66636675]])

MEAN, MEDIAN , MODE

In [26]:
a=np.arange(1,16,2) . reshape(2,4)
a

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [21]:
np.mean(a)

np.float64(7.0)

In [18]:
np.median(a)

np.float64(7.0)

minimum,maximum


In [33]:
a=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
print(np.min(a, axis = 0))

[1 2 3]


In [35]:
print(np.min(a, axis = 1))

[1 4 7]


In [36]:
print(np.max(a,axis=1))

[3 6 9]


In [37]:
print(np.max(a, axis = 0))

[7 8 9]


sorting

In [38]:
x = np.arange(1,10).reshape(3,3)
print(x)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
x[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [45]:
a=np.array([1,2,3,4,5,6,7])

a

array([1, 2, 3, 4, 5, 6, 7])

In [48]:
s=np.sort(a, kind='mergesort')
print(s)

[1 2 3 4 5 6 7]


matrix multiplication

In [51]:
a = np.arange(0,9).reshape(3,3)
b = np.ones((3,3))
print(a)
print()
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [53]:
np.dot(a,b)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [55]:
a.dot(b)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])