<a href="https://colab.research.google.com/github/sandhiyadurai/Data-Analytics/blob/main/numpy_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Reshaping in numpy

In [2]:
import numpy as np
a = np.array([3,6,9,12])
print(a)

[ 3  6  9 12]


In [4]:
a.reshape([2,2])
print(a)

[ 3  6  9 12]


In [5]:
np.reshape(a,(2,2))

array([[ 3,  6],
       [ 9, 12]])

In [14]:
y=np.arange(1,10) #--range of number in array
y
y=np.array(y) #-- change list to array
print(y)

[1 2 3 4 5 6 7 8 9]


In [31]:
 ##--- reshape is used to change the row and colunm size (only in acceptable size)
x=np.arange(1,10)
x=np.array(x)
print(x)

y = x.reshape(3,3)#---for reshaping declaration ar used not "np"
print(y)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


transpose and reshape array,matrixes,indexing


In [32]:
z = np.transpose(y)
print(z)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [33]:
y = z.reshape(3,3)
print(y)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [34]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
x[1,2]
x[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [39]:
a = np.arange(1,6)
b = np.arange(6,11)
print(a,b)

[1 2 3 4 5] [ 6  7  8  9 10]


In [41]:
x = np.vstack((a,b)) #----- what is apurpose of vstack-----vertical stach
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [42]:
x = np.hstack((a,b))#--- horizondal stack
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Concatedanation

In [45]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print(a)
print()
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [47]:
np.concatenate((a,b))


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [62]:
np.concatenate((a,b), axis = 1)#------- what is the menaing of this condition????!!!!!

AxisError: axis 1 is out of bounds for array of dimension 1

BRoadcastiong


In [52]:
a = np.arange(10,21,2)
b = np.array([[2],[2]])
print(a)
print(b)

[10 12 14 16 18 20]
[[2]
 [2]]


In [50]:
z = a+b
print(z)

[[12 14 16 18 20 22]
 [12 14 16 18 20 22]]


In [55]:
a = np.arange(10,21,2)
a

array([10, 12, 14, 16, 18, 20])

In [57]:
a+2



array([12, 14, 16, 18, 20, 22])

In [58]:
a-2

array([ 8, 10, 12, 14, 16, 18])

In [59]:
a*b

array([[20, 24, 28, 32, 36, 40],
       [20, 24, 28, 32, 36, 40]])